replicaCount: 1

frontendUrl: "https://beep.do-2023.fr/"
configMapName: backend-config
configService: beep-services

secret:
  appKey: "complete with the app key for the correct environment: prod or sta"

imagePullSecrets:
  - name: beep-registry

image:
  repository: milou666/beep-api
  pullPolicy: Always
  tag: 056b6d57
  port: 80
  smtpSecretName: beep-smtp-server

service:
  port: 80
  type: ClusterIP

ingress:
  enabled: true
  annotations: { traefik.ingress.kubernetes.io/router.entrypoints: web }
  hosts:
    - host: 'if you see this, it means that the ingress is not working properly'
      paths: ['/']

servicesReleaseName: beep-services
