replicaCount: 1

imagePullSecrets:
- name: beep-registry

image:
  repository: gitlab.polytech.umontpellier.fr:5050/beep/api
  pullPolicy: Always
  tag: 056b6d57
  port: 80
  configMapName: backend-config
  smtpSecretName: beep-smtp-server

service:
  port: 80
  type: ClusterIP

ingress:
  enabled: true
  annotations: {traefik.ingress.kubernetes.io/router.entrypoints: web}
  hosts:
  - host: 'if you see this, it means that the ingress is not working properly'
    paths: ['/']

servicesReleaseName: beep-services

