---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: beep-staging
spec:
  encryptedData:
    APP_KEY: AgCUQDzNi40amnkmE+cjfGkCBoyD94GGr6y4UOT6JXUwPKL2BteezJ+6gfp41jksZbFxKHUd21P5A3jHqgranDqDvmICdSurSaujN00xIdpOI/Uv/y1ZurHTHbVydOEM31uKU7UHUhiYDMuGD3aHncPlclswIDWnGA27a3NXwQ468jZvKRsXYkbe/DCK5SwfjMfUo25C7fbNnn3td7fslrOzTKYNAZmlAD1EW2CxlPq4fM6RxN2zHhxtPmJnihdxTwk0/xEoFBNkqp4nlPqCpgi0iOaIe7Lero6qNpSZQpV7tgaInltLTo3B/Nc/LFS+d2XB2HSLblmfcPSyp+kLFNaqb5l3Nf1XQ1d7iGvH4BF9Y1ADxxwGahVyAIQXbNwkqTnTsQZUzrih6akyXcb2vh0ZFi6LoRFgSzyaIkBH7D057/XP0L6whcNhdutpVFcN/zWKn0qBO1PTcFF6dkmeLEKDS8k+IkG9SdxmjEjlZYzoHSNo1gnlUGKmrxG32CbzP6lIO3BXKqVmUhG5oVm7tN3jYQCIk3D9mM888IM3I9YhivfZ51jBJ0tcLdRSpuRR/CUAKJeMtlnLBxFXPU0pPXNQ4gxSBhsARdPdIt/GmdGo5F+rK8BFHVj0HnOqHBhSzaOQ/i+crQ76aZYbg0neJItzVap/pLlhOaUMtQ+6EfvHjvuq1zC3jey90vVAVNgpOQqlbVCXtNxWVjWHC1pLEqjFU8oBHfb0
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: beep-staging
