stages:
- test
- publish
- deploy

include:
- template: Jobs/Dependency-Scanning.gitlab-ci.yml
- local: 'gitversion-ci-cd-plugin-extension.gitlab-ci.yml'

workflow:
  rules:
  # - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
  # - if: '$CI_COMMIT_BRANCH == "feat/ci-environment"'
  #   variables:
  #     DEPLOY_VARIABLE: develop
  #     CHART_NAME: beep-api-develop
  - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+-staging$/'
    variables:
      DEPLOY_VARIABLE: staging
      CHART_NAME: beep-api-staging
  - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/'
    variables:
      DEPLOY_VARIABLE: production
      CHART_NAME: beep-api
  - if: $DEPLOY_VARIABLE == "garbage"
    when: never

determineversion:
  stage: .pre
  rules:
  # - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
  # - if: '$CI_COMMIT_BRANCH == "feat/ci-environment"'
  - if: $CI_COMMIT_TAG
  extends: .gitversion_function


gemnasium-dependency_scanning:
  stage: test
  rules:
  - if: $CI_COMMIT_BRANCH == "main"
  - if: $CI_MERGE_REQUEST_IID

build-publish-image:
  stage: publish
  rules:
  # - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
  # - if: '$CI_COMMIT_BRANCH == "feat/ci-environment"'
  - if: $CI_COMMIT_TAG
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  dependencies:
  - determineversion
  script:
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$GitVersion_LegacySemVer
  environment:
    name: $DEPLOY_VARIABLE

package-publish-helm:
  stage: publish
  rules:
  # - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
  # - if: '$CI_COMMIT_BRANCH == "feat/ci-environment"'
  - if: $CI_COMMIT_TAG
  image: alpine/helm:latest
  dependencies:
  - determineversion
  script:
  - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O yq && chmod +x ./yq
  - export VERSION=$GitVersion_MajorMinorPatch
  # Echo pour débogage des variables d'environnement
  - "echo \"FRONT_URL_ENDPOINT: $FRONT_URL_ENDPOINT\""
  - "echo \"API_URL_ENDPOINT: $API_URL_ENDPOINT\""
  - "echo \"VERSION: $VERSION\""
  - "echo \"CHART_NAME: $CHART_NAME\""
  # Extraire le domaine de API_URL_ENDPOINT
  - DOMAIN=$(echo $API_URL_ENDPOINT | awk -F[/:] '{print $4}')
  - "echo \"Extracted DOMAIN: $DOMAIN\""
  # Modifier le fichier values.yaml
  - ls
  - ./yq -i ".ingress.hosts[0].host=\"$DOMAIN\"" helm/api/values.yaml
  - ./yq -i ".name=\"$CHART_NAME\"" helm/api/Chart.yaml
  # Vérifier le contenu de values.yaml après modification
  - cat helm/api/values.yaml
  - helm package helm/api --version $VERSION --app-version $VERSION
  - 'curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@$CHART_NAME-$VERSION.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/$DEPLOY_VARIABLE/charts"'
  environment:
    name: $DEPLOY_VARIABLE

publish-services:
  stage: publish
  image: alpine/helm:latest
  script:
  - wget https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
  - current_version=$(yq e '.version' helm/services/Chart.yaml)
  - IFS='.' read -ra version_parts <<< "$current_version"
  - major=$((version_parts[0] + 1))
  - new_version="$major.${version_parts[1]}.${version_parts[2]}"
  - yq e -i ".version = \"$new_version\"" helm/services/Chart.yaml
  - helm dependency update helm/services
  - helm package helm/services
  - 'curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@beep-services-$new_version.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/$DEPLOY_VARIABLE/charts"'
  rules:
  - changes:
    - helm/services/Chart.yaml
  environment:
    name: $DEPLOY_VARIABLE

