apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.image.configMapName }}
data:
  # kv format
  DB_HOST: "{{ .Release.Name }}-postgresql"
  DB_PORT: "{{ .Values.env.dbPort }}"
  DB_USER: "{{ .Values.env.dbUser }}"
  DB_DATABASE: "{{ .Values.postgresql.auth.database }}"
  S3_REGION: "us-east-1"
  S3_ENDPOINT: "http://{{ .Release.Name }}-minio:9000"
  S3_BUCKET_NAME: "{{ .Values.minio.defaultBuckets }}"
  REDIS_HOST: "{{ .Release.Name }}-redis-master"
  REDIS_PORT: "6379"

