---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.app.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    APP_KEY: "{{ .Values.secret.appKey }}"
  template:
    metadata:
      name: {{ .Values.app.existingSecret }}
      namespace: {{ .Release.Namespace }}
