apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "beep-backend-files.fullname" .) }}
  labels:
    {{- include "beep-backend-files.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "beep-backend-files.selectorLabels" . | nindent 4 }}
