---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.smtp.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    {{ .Values.smtp.hostKey }}: "{{ .Values.secret.smtp.host }}"
    {{ .Values.smtp.userKey }}: "{{ .Values.secret.smtp.username }}"
    {{ .Values.smtp.passwordKey }}: "{{ .Values.secret.smtp.password }}"
    {{ .Values.smtp.portKey }}: "{{ .Values.secret.smtp.port }}"
  template:
    metadata:
      name: {{ .Values.smtp.existingSecret }}
      namespace: {{ .Release.Namespace }}
